### ISSUE TITLE
CID not being applied to instances

### ISSUE THREAD

**Issue by L00k3r** [CrowdStrike/aws-ssm-distributor#84]
We have a large deployment using Terraform across multiple AWS accounts for tagging and installations and have noticed the CID is not applying to a few instances as part of the installation and registration process.
Support case and diagnostics are in case number 1260605 and we were referred here to open an issue.

**Comment by ffalor** [comment]
Hey @L00k3r based on the logs I saw it looks like the sensor was not installed. I'd need to know more about the SSM run itself, but most of the time this is due to the instance being targeted but is not in SSM correctly.

There are a few ways to check this:
- Go to fleet manager in aws and see if the instance you are referencing shows up. If it does not then the instance is not managed by SSM.
- Go to the output of the association apply that targeted the instance and check if the `ExecuteLinuxDistributor` step is pending. If the targeted machine is a linux machine and this step is showed as pending despite the association shows completed this means the instance is not managed by SSM. More info on why it shows pending [here](https://github.com/CrowdStrike/aws-ssm-distributor/blob/main/official-package/README.md#why-do-some-automation-steps-stay-pending)

The following is required for SSM to manage a instance:
- Network connectivity to SSM.
- A instance profile with proper permissions applied to the instance.
- The SSM agent to be installed.

Could you check if the instance is ssm managed and provide me with the logs from the run? (Redact sensitive info like oauth2 tokens, etc)
