### ISSUE TITLE
Cross account Secrets Manager Secret support

### ISSUE THREAD

**Issue by smcmahon-starz** [CrowdStrike/aws-ssm-distributor#97]
I was reviewing the official package contents, and it appears that the SSM infrastructure and associated SSM Distributor packages presently require the Secrets Manager secret to reside in each account/region where the Crowdstrike SSM distribution infrastructure resides.

First is it correct that The CrowdStrike distribution SSM distribution templates and Distributor Falcon packages do not support using a cross account AWS secret? From what I have seen, only a secret name can be used in the CrowdStrike-FalconSensorDeploy automation document and the CrowdStrike-Sensor-Deploy that is created by this repository.

If so, then could the team consider adding the ability to reference a cross account secret (ie via ARN)? This would make it easier/more secure to administer the CrowdStrike credentials; the secret resource policy could be used to restrict access. For now we will probably use System Manager parameter store where we share out the parameters via AWS Resource Access Manager, but we will then need to use an Service Control Policy to prevent unwanted access from devs, etc who might have the ability to view in certain AWS accounts where they have elevated access. Thanks

... After reviewing RAM SSM parameter share, unfortunately that also requires reference via ARN as well (could have just shared to specific IAM roles rather than use an SCP to limit access, but that is a moot point).

**Comment by ffalor** [comment]
Hey @smcmahon-starz to give some context on what happens. We are using the `executeScript` automation action to get the secrets out of either SSM Parameter store or Secrets manager. The code is written in python, and uses boto3 to do this.  

From my understanding providing an arn and accessing cross account secrets is supported by boto3 and secrets manager so there should be no issue. Whatever is passed to the `SecretsManagerSecretName` parameter is passed directly to AWS which is why a ARN will work. This also assumes the role that the automation document is running under has the appropriate permissions to do this cross account lookup. 

So like you mentioned, ARNs will work so you should be good to go!
